version: '3.7'
services: 
        samba:
                restart: always
                build:         
                        context: .
                        dockerfile: Dockerfile.samba
                ports :
                        - "139:139"
                        - "445:445"
                volumes:
                        - "/mnt/samba:/samba"
                container_name: samba_server
        dlna:
                restart: always
                build: 
                        context: .
                        dockerfile: Dockerfile.dlna
                volumes:
                        - "/mnt/samba:/samba"
                container_name: dlna_server
                network_mode: host
