# 2.4 due to device_cgroup_rules being remove from later schema
#https://github.com/docker/compose/pull/6974
version: '2.4'
services: 
        samba:
                restart: always
                build:         
                        context: .
                        dockerfile: Dockerfile.samba
                volumes:
                        - "/mnt/docker/samba:/samba"
                networks:
                    ipvlan:
                container_name: samba
        dlna:
                restart: always
                build: 
                        context: .
                        dockerfile: Dockerfile.dlna
                volumes:
                        - "/mnt/docker/samba:/samba"
                networks:
                    ipvlan:
                container_name: dlna
        print:
                restart: always
                build: 
                        context: .
                        dockerfile: Dockerfile.print
                volumes:
                        - "/var/run/dbus:/var/run/dbus"
                container_name: cups
                networks:
                    ipvlan:
                #rules allow access to shared usb devices 
                device_cgroup_rules:
                  - 'c 189:* rmw'
                volumes:
                        - "/dev/bus/usb:/dev/bus/usb"
        pihole:
            container_name: pihole
            image: pihole/pihole:dev
            environment:
              TZ: 'Europe/London'
              WEBPASSWORD: "password"
            volumes:
               - '/mnt/docker/pihole/etc-pihole/:/etc/pihole/'
               - '/mnt/docker/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
            dns:
              - 127.0.0.1
              - 1.1.1.1
            cap_add:
              - NET_ADMIN
            networks:
                    ipvlan:
                        ipv4_address: 192.168.0.254
            restart: unless-stopped
            
networks:
             ipvlan:
               name: ipvlan
               driver: ipvlan
               driver_opts:
                       parent: "wlan0"
               ipam:
                       config:
                               - subnet: 192.168.0.0/24
                                 gateway: 192.168.0.1
                                 ip_range: 192.168.0.192/26
                                 aux_addresses:
                                         host: 192.168.0.190
#ip link add docker-ipvlan link wlan0 type ipvlan
#ip addr add 192.168.0.190/32 dev docker-ipvlan
#ip link set docker-ipvlan up
#ip route add 192.168.1.192/26 dev docker-ipvlan up
