version: '3.7'
services: 
        samba:
                restart: always
                build:         
                        context: .
                        dockerfile: Dockerfile.samba
                ports :
                        - "139:139"
                        - "445:445"
                volumes:
                        - "/mnt/samba:/samba"
                container_name: samba_server
        dlna:
                restart: always
                build: 
                        context: .
                        dockerfile: Dockerfile.dlna
                volumes:
                        - "/mnt/samba:/samba"
                container_name: dlna_server
                network_mode: host
        print:
                restart: always
                build: 
                        context: .
                        dockerfile: Dockerfile.print
                volumes:
                        - "/var/run/dbus:/var/run/dbus"
                container_name: print_server
                network_mode: host
                volumes:
                        - "/dev/bus/usb:/dev/bus/usb"
                devices:
                        - "/dev/brother-printer:/dev/brother-printer"
