# 2.4 due to device_cgroup_rules being remove from later schema
#https://github.com/docker/compose/pull/6974
version: '2.4'
services: 
        samba:
                restart: always
                build:         
                        context: .
                        dockerfile: Dockerfile.samba
                ports :
                        - "139:139"
                        - "445:445"
                volumes:
                        - "/mnt/samba:/samba"
                container_name: samba_server
        dlna:
                restart: always
                build: 
                        context: .
                        dockerfile: Dockerfile.dlna
                volumes:
                        - "/mnt/samba:/samba"
                container_name: dlna_server
                network_mode: host
        print:
                restart: always
                build: 
                        context: .
                        dockerfile: Dockerfile.print
                volumes:
                        - "/var/run/dbus:/var/run/dbus"
                container_name: print_server
                network_mode: host
                #rules allow access to shared usb devices 
                device_cgroup_rules:
                  - 'c 189:* rmw'
                volumes:
                        - "/dev/bus/usb:/dev/bus/usb"
