# 2.4 due to device_cgroup_rules being remove from later schema
#https://github.com/docker/compose/pull/6974
version: '2.4'
services: 
        samba:
                container_name: samba
                restart: always
                build:         
                        context: .
                        dockerfile: Dockerfile.samba
                volumes:
                        - "/mnt/docker/samba:/samba"
                ports :
                        - "139:139"
                        - "445:445"
        dlna:
                container_name: dlna
                network_mode: host
                restart: always
                build: 
                        context: .
                        dockerfile: Dockerfile.dlna
                volumes:
                        - "/mnt/docker/samba:/samba"
        print:
                container_name: print
                network_mode: host
                restart: always
                build: 
                        context: .
                        dockerfile: Dockerfile.print
                volumes:
                        - "/var/run/dbus:/var/run/dbus"
                #rules allow access to shared usb devices 
                device_cgroup_rules:
                  - 'c 189:* rmw'
                volumes:
                        - "/dev/bus/usb:/dev/bus/usb"
